routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{lang}', 'LanguageController@index');
Route::middleware(['Lang', 'Visitors'])->group(function () { 



	Route::post('/join', 'AuthenticationController@register')->name('join');
	Auth::routes();	

	// Front end
	Route::middleware(['Maintenance'])->group(function () { 
	
		Route::get('/', function () {
		    return view('welcome');
		});
		

		Route::get('/home', 'HomeController@index')->name('home');

		

	});


	/**
	* Admin Routing
	*/
	Route::group(['prefix' => ADMIN_PREFIX(),'middleware' => 'roles', 'roles' => ['Admin', 'Editor']], function(){

		Route::get('/', 'Backend\Dashboard\DashboardController@index')->name('Admin');

		// Route::get('/users', 'Backend\Users\UsersController@index')->name('Admin.users');
		Route::resource('/users', 'Backend\Users\UsersController', ['as' => 'admin']);
		Route::post('/users/update/account_settings', 'Backend\Users\UsersController@account_settings')->name('settings.account_settings');
		Route::get('/users/activity/{id}', 'Backend\Users\UsersController@showActivity')->name('user.activity.backend');

		Route::resource('/admins', 'Backend\Administrators\AdministratorsController', ['as' => 'admin']);


		// Languages
		Route::get('/languages', 'Backend\Settings\Languages\LanguagesController@index')->name('admin.languages.index');
		Route::get('/languages/translations/{lang}', 'Backend\Settings\Languages\LanguagesController@show')->name('admin.languages.show');
		Route::get('/languages/new', 'Backend\Settings\Languages\LanguagesController@newLang')->name('admin.languages.newLang');
		Route::get('/languages/{lang}', 'Backend\Settings\Languages\LanguagesController@editLang')->name('admin.languages.editLang');
		
		Route::post('/languages/set-default-language', 'Backend\Settings\Languages\LanguagesController@setDefaultLanguage')->name('admin.languages.setDefaultLanguage');

		Route::post('/languages/add-new-lang', 'Backend\Settings\Languages\LanguagesController@addNewLang')->name('admin.languages.addNewLang');

		Route::post('/languages/delete/{lang}', 'Backend\Settings\Languages\LanguagesController@deleteLang')->name('admin.languages.deleteLang');


	});

});

app/Models/Backend/App.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class App extends Model
{
    //
}

app/Models/Backend/AppSetting.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class AppSetting extends Model
{
    //
}

app/Models/Backend/Role.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users()
    {
    	return $this->belongsToMany('App\Models\Backend\User', 'user_role', 'role_id', 'user_id');
    }
}

app/Models/Backend/User.php
<?php

namespace App\Models\Backend;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

use DB;
use Cache;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    /**
    |
    |--------------------------------------------------------------------------
    | Check if user is online or offline
    |--------------------------------------------------------------------------
    |
    */
    public function isOnline()
    {
        return Cache::has('user-is-online-' . $this->id);
    }





    public function settings()
    {
        return $this->hasOne('App\Models\Pub\UserSetting', 'user_id');
        // $settings = DB::table('user_settings')->where('user_id', Auth::user()->id)->first();
        // return DB::table('user_settings')->get();
    }



    public function activities()
    {
        return $this->hasMany('App\Models\Pub\UserActivity', 'user_id');
        // $settings = DB::table('user_settings')->where('user_id', Auth::user()->id)->first();
        // return DB::table('user_settings')->get();
    }






    public function roles()
    {
        return $this->belongsToMany('App\Models\Backend\Role', 'user_role', 'user_id', 'role_id');
    }


    /**
    |--------------------------------------------------------------------------
    | Has any role?
    |--------------------------------------------------------------------------
    |
    | This method to check if current users has any role in the Role Table
    | or not.
    |
    */
    public function hasAnyRole($roles)
    {
        if (is_array($roles))
        {
            // Loop the index.
            foreach ($roles as $role) {
                if ($this->hasRole($role))
                {
                    return true;
                }
            }
        }

        else
        {          
            if ($this->hasRole($roles))
            {
                return true;
            }
        }

    }


    /**
    |--------------------------------------------------------------------------
    | Has role?
    |--------------------------------------------------------------------------
    |
    | This method to check if role exist in the Database
    | 
    |
    */
    public function hasRole($role)
    {
        if (is_array($role))
        {
            // Loop the index.
            foreach ($role as $rol) {
                if ($this->roles()->where('name', $rol)->first())
                {
                    return true;
                }
            }
        }

        else
        {          
            if ($this->roles()->where('name', $role)->first())
            {
                return true;
            }
        }

        return false;

        // if ($this->roles()->where('name', $role)->first())
        // {
        //     return true;
        // }

        // return false;
    }








}

app/Http/Controllers/Backend/Administrators/AdministratorsController.php
<?php

namespace App\Http\Controllers\Backend\Administrators;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Backend\User;
use App\Models\Backend\Role;

class AdministratorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = Role::where('name', 'Admin')
        ->first()
        ->users()
        ->get();  



        $users_counter = Role::where('name', 'Admin')
        ->first()->users()->count();  

        return view('Backend.Administrators.index', compact('users', 'users_counter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Backend\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Backend\User;
use App\Models\Backend\Role;
use Carbon\Carbon;

class DashboardController extends Controller
{
    public function index()
    {

    	$total_users = Role::where('name', 'User')->first()->users()->count();
    	
    	$today_registered_users= Role::where('name', 'User')
    													->first()->users()
    													->whereDate('users.created_at', Carbon::today())->count();

    	return view('Backend.Dashboard.index', compact('total_users', 'today_registered_users'));
    }
}

app/Http/Controllers/Backend/Settings/Languages/LanguagesController.php
<?php

namespace App\Http\Controllers\Backend\Settings\Languages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Pub\Language;
use App\Models\Pub\Translation;
use App\Models\Backend\AppSetting as Setting;

class LanguagesController extends Controller
{

    public function index()
    {
        $default_lang = Setting::where('name', '=', 'Language')->first();
        $languages = Language::all();
        return view('Backend.Settings.Languages.index', compact('languages', 'default_lang'));
    }

    public function setDefaultLanguage(Request $request)
    {
        $default_lang = Setting::where('name', '=', 'Language')->first();
        $default_lang->value = $request->default_lang;
        $default_lang->update();

        if ($default_lang->update())
        {
            return back();
        }
    }


    public function show($lang)
    {
        $language = Language::where('name', '=', $lang)->first();

        if ($language)
        {

            $translations = Translation::where('lang_shortcut', '=', $language->shortcut)->get();

            if ($translations) {
                return view('Backend.Settings.Languages.show', compact('language', 'translations'));
            }
            else
            {
                abort(404);
            }
        }

        else
        {
            abort(404);
        }
    }


    // New Language
    public function newLang()
    {
        return view('Backend.Settings.Languages.new');
    }

    // Add new Languages & Default Translation
    public function addNewLang(Request $request)
    {
        // Save Language
        $language = new Language;

        $language->name = $request->name;
        $language->shortcut = $request->shortcut;
        $language->code = $request->code;
        $language->icon_code = $request->icon_code;
        $language->dirction = $request->dirction;
        $language->status = $request->status;

        $language->save();

        // Save Default Translations
        $translation = Translation::where('lang_shortcut', '=', 'en')->get();
        
        foreach ($translation as $trans) {
            Translation::create([
                'lang_shortcut' => $language->shortcut,
                'key' => $trans->key,
                'value' => $trans->value
            ]);
        }
   
        return redirect(route('admin.languages.index'));
    }

    // Edit Language
    public function editLang($lang)
    {
        $language = Language::where('shortcut', '=', $lang)->first();
        if ($language)
        {
            return view('Backend.Settings.Languages.edit', compact('language'));
        }
        else
        {
            abort(404);
        }
        
    }

    // Delete Language & Translations
    public function deleteLang($lang)
    {
        // Delete Language
        $language = Language::where('shortcut', '=', $lang)->delete();   


        // Delete Language Translations
        $translation = Translation::where('lang_shortcut', '=', $lang)->delete();

        // If successfully deleted return to language index
        if ($translation && $language)
        {
            return redirect(route('admin.languages.index'));
        }
        // If not successfully deleted return error message.
        else
        {
            echo 'error by delete.';
        }
        
    }


}

app/Http/Controllers/Backend/Users/UsersController.php
<?php

namespace App\Http\Controllers\Backend\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Backend\User;
use App\Models\Backend\Role;
use App\Models\Pub\UserSetting as Setting;
use App\Models\Pub\UserActivity as Activity;
// use App\Models\Public\UserSetting;

use DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = Role::where('name', 'User')->first()->users()->get();  
        $users_counter = Role::where('name', 'User')->first()->users()->count();  

        return view('Backend.Users.index', compact('users', 'users_counter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $where = array('id' => $id);
        // $data['product_info'] = Product::where($where)->first();
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        
        if ($user)
        {
            $activity_count = Activity::where('user_id', $user->id)->count();
            $activities = Activity::where('user_id', $user->id)->paginate(5);            
            return view('Backend.Users.show', compact('user', 'activity_count', 'activities'));
        }
        else
        {
            abort(404);
        }
    }

    public function showActivity($id)
    {
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        $activity_count = Activity::where('user_id', $user->id)->count();  

        if ($user)
        {
            return view('Backend.Users.activity', compact('user', 'activity_count'));
        }
        else
        {
            abort(404);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        
        if ($user)
        {
            return view('Backend.Users.edit', compact('user'));
        }
        else
        {
            abort(404);
        }
    }


    public function account_settings(Request $request)
    {

        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $request->user_id)
        ->first();

       $setting = Setting::find($request->user_id);


       if ($user)
       {
        $user->is_verified = $request->is_verified ? 1 : 0 ?? 0;
        $user->is_active = $request->is_active ? 1 : 0 ?? 0;

        dd($user);
       }

       if ($setting)
       {

        // Get actions section values
        $setting->can_user_create_shop = $request->can_user_create_shop ? 1 : 0 ?? 0;
        $setting->can_user_sell = $request->can_user_sell ? 1 : 0 ?? 0;
        $setting->can_user_buy = $request->can_user_buy ? 1 : 0 ?? 0;
        $setting->can_user_comment = $request->can_user_comment ? 1 : 0 ?? 0;
        $setting->can_user_review = $request->can_user_review ? 1 : 0 ?? 0;
        $setting->can_user_contact_support_team = $request->can_user_contact_support_team ? 1 : 0 ?? 0;
        $setting->can_visitor_show_user_shop = $request->can_visitor_show_user_shop ? 1 : 0 ?? 0;
        
        // Save Data
        // dd($setting);
        $setting->save();
       }

       return back();




       // 
       // $setting->can_user_create_shop = $can_user_create_shop;

       // $setting->save();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Backend/Administrators/index.blade.php
{{-- Extends The Root --}}
@extends('backend.root')

{{-- Start Css Vendors --}}
@section('vendor-css')
<link rel="stylesheet" type="text/css" href="{{asset('static/backend/app-assets/vendors/css/tables/datatable/datatables.min.css')}}">
@stop {{-- End Css Vendors --}}


{{-- Start Pages Ttitle --}}

@section('pages-title')
Dashboard
@stop

{{-- End Pages Ttitle --}}





{{-- Start Page Content --}}
@section('content')

@if ($users_counter == 0)


 <section class="empty-records">
     <img class="no-data-image" src="{{asset('static/backend/assets/images/errors/no_data.svg')}}">
     <div class="no-data-msg">There are no users yet!</div>
 </section>


@else

<!-- Zero configuration table -->
<section id="column-selectors">
    <div class="row">
        <div class="col-12">
            <div class="card flooma-card-table">
                <div class="card-header d-flex justify-content-between ">
                    <h4 class="font-large-1">
                        
                        Administrators

                    </h4>
										<a href="#" class="btn btn-light-secondary glow mr-1 mb-1">
											<i class='bx bx-plus'></i>
											New admin
                		</a>
                </div>
                <div class="card-content">
                    <div class="card-body card-dashboard">

                        <div class="table-responsive flooma-table">
                            <table class="table table-striped dataex-html5-selectors">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Username</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>E-Mail Address</th>
                                        <th>Role</th>
                                        <th>Register date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	@foreach($users as $user)
                                    <tr>
                                    	<td>{{$user->id}}</td>
 
                                        <td class="py-1 line-ellipsis">

                                            @if ($user->profile_image === null)

                                                <img class="rounded-circle mr-1" src="{{asset('static/public/user/default.png')}}" alt="card" height="24" width="24">

                                            @else

                                            <img class="rounded-circle mr-1" src="{{asset('static/public/user/')}} {{$user->profile_image}}" alt="card" height="24" width="24">

                                            @endif
                                          

                                          {{$user->name}}
                                        </td>     

                                        <td>
                                            @if ($user->first_name === null)
                                            <span style="cursor: pointer;" 
                                            class="tooltip-light" 
                                            data-toggle="tooltip" 
                                            data-placement="top"
                                            data-original-title="Not available">
                                                N/A
                                            </span>                                            
                                                
                                            @else
                                               {{$user->first_name}}
                                            @endif
                                        </td>
 

                                        <td>
                                            @if ($user->last_name === null)
                                            <span style="cursor: pointer;" 
                                            data-toggle="tooltip" 
                                            data-placement="top" title="" 
                                            data-original-title="Not available">
                                                N/A
                                            </span>                                            
                                                
                                            @else
                                               {{$user->last_name}}
                                            @endif
                                        </td>
 

                                        <td>
                                            {{$user->email}}
                                            @if ($user->email_verified_at === null)
                                                <i class='bx bx-x-circle' 
                                                style="cursor: pointer;position: absolute;margin-left: 5px;margin-top: 1px;" 
                                                data-trigger="hover"  
                                                data-toggle="popover" 
                                                data-placement="top" 
                                                data-container="body" 
                                                data-original-title="{{$user->email}}" 
                                                data-content="This E-Mail Address is Not Verified"></i>

     
                                            @else
                                                <i class='bx bx-check-circle' 
                                                style="cursor: pointer;position: absolute;margin-left: 5px;margin-top: 1px;" 
                                                data-trigger="hover"  
                                                data-toggle="popover" 
                                                data-placement="top" 
                                                data-container="body" 
                                                data-original-title="{{$user->email}}" 
                                                data-content="This E-Mail Address is Verified"></i>                                            
                                            @endif
                                            


                                        </td>
 {{--                                        <td>Edinburgh</td>
                                        <td class="text-success py-1">Active</td> --}}

                                        <td>
                                                
                                            @if ($user->hasRole('Admin'))
                                                <div class="badge badge-light-secondary">Admin</div>

                                            @elseif ($user->hasRole('Editor'))
                                                <div class="badge badge-light-secondary ">Editor</div>

                                            @endif

                                        </td>

                                        <td>
                                            <span style="cursor: pointer;" 
                                            data-toggle="tooltip" 
                                            data-placement="top" title="" 
                                            data-original-title="{{$user->created_at->format('d.m.Y')}}">
                                                {{$user->created_at->diffForHumans()}}
                                            </span>                                             
                                        </td>

                                        <td>


                                            <a href="{{route('admin.users.index')}}/{{$user->id}}" 
                                            class="btn flooma-btn btn-icon btn-light-secondary"
                                            data-toggle="tooltip" 
                                            data-placement="top" title="" 
                                            data-original-title="View">
                                                <i class='bx bx-show-alt'></i>
                                            </a>

                                            <a href="{{route('admin.users.index')}}/{{$user->id}}/edit" 
                                            class="btn flooma-btn btn-icon btn-light-secondary"
                                            data-toggle="tooltip" 
                                            data-placement="top" title="" 
                                            data-original-title="Edit">
                                                <i class='bx bx-edit-alt'></i>
                                            </a>

                       
                      
                                        	<a href="{{$user->id}}" class="btn flooma-btn btn-icon btn-light-secondary" data-toggle="modal" data-target="#confirmationDelete">
                                        		<i class='bx bx-trash' ></i>
                                        	</a>
                                        	
                                        </td>
                                    </tr>

    								<div class="modal fade" id="confirmationDelete" tabindex="-1" role="dialog"
    								  aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    								  <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable"
    								    role="document">
    								    <div class="modal-content">
    								      <div class="modal-header">
    								        <h5 class="modal-title" id="exampleModalCenterTitle">Delete user</h5>
    								        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    								          <i class="bx bx-x"></i>
    								        </button>
    								      </div>
    								      <div class="modal-body">
    								        <p>
    								          Are you sure you want to delete this {{$user->id
                                              }} ?
    								        </p>
    								      </div>
    								      <div class="modal-footer">
    								        <button type="button" class="btn btn-light-secondary" data-dismiss="modal">
    								          <i class="bx bx-x d-block d-sm-none"></i>
    								          <span class="d-none d-sm-block">No</span>
    								        </button>
    								        <button type="button" class="btn btn-secondary ml-1" data-dismiss="modal">
    								          <i class="bx bx-check d-block d-sm-none"></i>
    								          <span class="d-none d-sm-block">Yes</span>
    								        </button>
    								      </div>
    								    </div>
    								  </div>
    								</div>

                                   @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ Zero configuration table -->

@endif {{-- End if of Counter --}}


@stop





{{-- Start Js Vendors --}}
@section('vendor-js')
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/datatables.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/buttons.html5.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/buttons.print.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/pdfmake.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/vendors/js/tables/datatable/vfs_fonts.js')}}"></script>
@stop{{-- End Js Vendors --}}

{{-- Start Js pages --}}
@section('pages-js')
<script src="{{asset('static/backend/app-assets/js/scripts/datatables/datatable.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/js/scripts/modal/components-modal.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/js/scripts/popover/popover.min.js')}}"></script>
@stop{{-- End Js pages --}}