routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{lang}', 'LanguageController@index');
Route::middleware(['Lang', 'Visitors'])->group(function () { 



	Route::post('/join', 'AuthenticationController@register')->name('join');
	Auth::routes();	

	// Front end
	Route::middleware(['Maintenance'])->group(function () { 
	
		Route::get('/', function () {
		    return view('welcome');
		});
		

		Route::get('/home', 'HomeController@index')->name('home');

		

	});


	/**
	* Admin Routing
	*/
	Route::group(['prefix' => ADMIN_PREFIX(),'middleware' => 'roles', 'roles' => ['Admin', 'Editor']], function(){

		Route::get('/', 'Backend\Dashboard\DashboardController@index')->name('Admin');

		// Route::get('/users', 'Backend\Users\UsersController@index')->name('Admin.users');
		Route::resource('/users', 'Backend\Users\UsersController', ['as' => 'admin']);
		Route::post('/users/update/account_settings', 'Backend\Users\UsersController@account_settings')->name('settings.account_settings');
		Route::get('/users/activity/{id}', 'Backend\Users\UsersController@showActivity')->name('user.activity.backend');

		Route::resource('/admins', 'Backend\Administrators\AdministratorsController', ['as' => 'admin']);


		// Languages
		Route::get('/languages', 'Backend\Settings\Languages\LanguagesController@index')->name('admin.languages.index');
		Route::get('/languages/translations/{lang}', 'Backend\Settings\Languages\LanguagesController@show')->name('admin.languages.show');
		Route::get('/languages/new', 'Backend\Settings\Languages\LanguagesController@newLang')->name('admin.languages.newLang');
		Route::get('/languages/{lang}', 'Backend\Settings\Languages\LanguagesController@editLang')->name('admin.languages.editLang');
		
		Route::post('/languages/set-default-language', 'Backend\Settings\Languages\LanguagesController@setDefaultLanguage')->name('admin.languages.setDefaultLanguage');

		Route::post('/languages/add-new-lang', 'Backend\Settings\Languages\LanguagesController@addNewLang')->name('admin.languages.addNewLang');

		Route::post('/languages/delete/{lang}', 'Backend\Settings\Languages\LanguagesController@deleteLang')->name('admin.languages.deleteLang');


	});

});

app/Models/Backend/App.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class App extends Model
{
    //
}

app/Models/Backend/AppSetting.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class AppSetting extends Model
{
    //
}

app/Models/Backend/Role.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function users()
    {
    	return $this->belongsToMany('App\Models\Backend\User', 'user_role', 'role_id', 'user_id');
    }
}

app/Models/Backend/User.php
<?php

namespace App\Models\Backend;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

use DB;
use Cache;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    /**
    |
    |--------------------------------------------------------------------------
    | Check if user is online or offline
    |--------------------------------------------------------------------------
    |
    */
    public function isOnline()
    {
        return Cache::has('user-is-online-' . $this->id);
    }





    public function settings()
    {
        return $this->hasOne('App\Models\Pub\UserSetting', 'user_id');
        // $settings = DB::table('user_settings')->where('user_id', Auth::user()->id)->first();
        // return DB::table('user_settings')->get();
    }



    public function activities()
    {
        return $this->hasMany('App\Models\Pub\UserActivity', 'user_id');
        // $settings = DB::table('user_settings')->where('user_id', Auth::user()->id)->first();
        // return DB::table('user_settings')->get();
    }






    public function roles()
    {
        return $this->belongsToMany('App\Models\Backend\Role', 'user_role', 'user_id', 'role_id');
    }


    /**
    |--------------------------------------------------------------------------
    | Has any role?
    |--------------------------------------------------------------------------
    |
    | This method to check if current users has any role in the Role Table
    | or not.
    |
    */
    public function hasAnyRole($roles)
    {
        if (is_array($roles))
        {
            // Loop the index.
            foreach ($roles as $role) {
                if ($this->hasRole($role))
                {
                    return true;
                }
            }
        }

        else
        {          
            if ($this->hasRole($roles))
            {
                return true;
            }
        }

    }


    /**
    |--------------------------------------------------------------------------
    | Has role?
    |--------------------------------------------------------------------------
    |
    | This method to check if role exist in the Database
    | 
    |
    */
    public function hasRole($role)
    {
        if (is_array($role))
        {
            // Loop the index.
            foreach ($role as $rol) {
                if ($this->roles()->where('name', $rol)->first())
                {
                    return true;
                }
            }
        }

        else
        {          
            if ($this->roles()->where('name', $role)->first())
            {
                return true;
            }
        }

        return false;

        // if ($this->roles()->where('name', $role)->first())
        // {
        //     return true;
        // }

        // return false;
    }








}

app/Http/Controllers/Backend/Administrators/AdministratorsController.php
<?php

namespace App\Http\Controllers\Backend\Administrators;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Backend\User;
use App\Models\Backend\Role;

class AdministratorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = Role::where('name', 'Admin')
        ->first()
        ->users()
        ->get();  



        $users_counter = Role::where('name', 'Admin')
        ->first()->users()->count();  

        return view('Backend.Administrators.index', compact('users', 'users_counter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Backend\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Backend\User;
use App\Models\Backend\Role;
use Carbon\Carbon;

class DashboardController extends Controller
{
    public function index()
    {

    	$total_users = Role::where('name', 'User')->first()->users()->count();
    	
    	$today_registered_users= Role::where('name', 'User')
    													->first()->users()
    													->whereDate('users.created_at', Carbon::today())->count();

    	return view('Backend.Dashboard.index', compact('total_users', 'today_registered_users'));
    }
}

app/Http/Controllers/Backend/Settings/Languages/LanguagesController.php
<?php

namespace App\Http\Controllers\Backend\Settings\Languages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Pub\Language;
use App\Models\Pub\Translation;
use App\Models\Backend\AppSetting as Setting;

class LanguagesController extends Controller
{

    public function index()
    {
        $default_lang = Setting::where('name', '=', 'Language')->first();
        $languages = Language::all();
        return view('Backend.Settings.Languages.index', compact('languages', 'default_lang'));
    }

    public function setDefaultLanguage(Request $request)
    {
        $default_lang = Setting::where('name', '=', 'Language')->first();
        $default_lang->value = $request->default_lang;
        $default_lang->update();

        if ($default_lang->update())
        {
            return back();
        }
    }


    public function show($lang)
    {
        $language = Language::where('name', '=', $lang)->first();

        if ($language)
        {

            $translations = Translation::where('lang_shortcut', '=', $language->shortcut)->get();

            if ($translations) {
                return view('Backend.Settings.Languages.show', compact('language', 'translations'));
            }
            else
            {
                abort(404);
            }
        }

        else
        {
            abort(404);
        }
    }


    // New Language
    public function newLang()
    {
        return view('Backend.Settings.Languages.new');
    }

    // Add new Languages & Default Translation
    public function addNewLang(Request $request)
    {
        // Save Language
        $language = new Language;

        $language->name = $request->name;
        $language->shortcut = $request->shortcut;
        $language->code = $request->code;
        $language->icon_code = $request->icon_code;
        $language->dirction = $request->dirction;
        $language->status = $request->status;

        $language->save();

        // Save Default Translations
        $translation = Translation::where('lang_shortcut', '=', 'en')->get();
        
        foreach ($translation as $trans) {
            Translation::create([
                'lang_shortcut' => $language->shortcut,
                'key' => $trans->key,
                'value' => $trans->value
            ]);
        }
   
        return redirect(route('admin.languages.index'));
    }

    // Edit Language
    public function editLang($lang)
    {
        $language = Language::where('shortcut', '=', $lang)->first();
        if ($language)
        {
            return view('Backend.Settings.Languages.edit', compact('language'));
        }
        else
        {
            abort(404);
        }
        
    }

    // Delete Language & Translations
    public function deleteLang($lang)
    {
        // Delete Language
        $language = Language::where('shortcut', '=', $lang)->delete();   


        // Delete Language Translations
        $translation = Translation::where('lang_shortcut', '=', $lang)->delete();

        // If successfully deleted return to language index
        if ($translation && $language)
        {
            return redirect(route('admin.languages.index'));
        }
        // If not successfully deleted return error message.
        else
        {
            echo 'error by delete.';
        }
        
    }


}

app/Http/Controllers/Backend/Users/UsersController.php
<?php

namespace App\Http\Controllers\Backend\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Backend\User;
use App\Models\Backend\Role;
use App\Models\Pub\UserSetting as Setting;
use App\Models\Pub\UserActivity as Activity;
// use App\Models\Public\UserSetting;

use DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = Role::where('name', 'User')->first()->users()->get();  
        $users_counter = Role::where('name', 'User')->first()->users()->count();  

        return view('Backend.Users.index', compact('users', 'users_counter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $where = array('id' => $id);
        // $data['product_info'] = Product::where($where)->first();
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        
        if ($user)
        {
            $activity_count = Activity::where('user_id', $user->id)->count();
            $activities = Activity::where('user_id', $user->id)->paginate(5);            
            return view('Backend.Users.show', compact('user', 'activity_count', 'activities'));
        }
        else
        {
            abort(404);
        }
    }

    public function showActivity($id)
    {
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        $activity_count = Activity::where('user_id', $user->id)->count();  

        if ($user)
        {
            return view('Backend.Users.activity', compact('user', 'activity_count'));
        }
        else
        {
            abort(404);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $id)
        ->first();

        
        if ($user)
        {
            return view('Backend.Users.edit', compact('user'));
        }
        else
        {
            abort(404);
        }
    }


    public function account_settings(Request $request)
    {

        $user = Role::where('name', 'User')
        ->first()
        ->users()
        ->where('users.id', $request->user_id)
        ->first();

       $setting = Setting::find($request->user_id);


       if ($user)
       {
        $user->is_verified = $request->is_verified ? 1 : 0 ?? 0;
        $user->is_active = $request->is_active ? 1 : 0 ?? 0;

        dd($user);
       }

       if ($setting)
       {

        // Get actions section values
        $setting->can_user_create_shop = $request->can_user_create_shop ? 1 : 0 ?? 0;
        $setting->can_user_sell = $request->can_user_sell ? 1 : 0 ?? 0;
        $setting->can_user_buy = $request->can_user_buy ? 1 : 0 ?? 0;
        $setting->can_user_comment = $request->can_user_comment ? 1 : 0 ?? 0;
        $setting->can_user_review = $request->can_user_review ? 1 : 0 ?? 0;
        $setting->can_user_contact_support_team = $request->can_user_contact_support_team ? 1 : 0 ?? 0;
        $setting->can_visitor_show_user_shop = $request->can_visitor_show_user_shop ? 1 : 0 ?? 0;
        
        // Save Data
        // dd($setting);
        $setting->save();
       }

       return back();




       // 
       // $setting->can_user_create_shop = $can_user_create_shop;

       // $setting->save();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Backend/Users/activity.blade.php
{{-- Extends The Root --}}
@extends('backend.root')

{{-- Start Css Vendors --}}
@section('vendor-css')

@stop {{-- End Css Vendors --}}


{{-- Start Pages Ttitle --}}

@section('pages-title')
Dashboard
@stop

{{-- End Pages Ttitle --}}





{{-- Start Page Content --}}
@section('content')




<section class="page-user-profile">
  <div class="row">
    <div class="col-12">


      <!-- user profile content section start -->
      <div class="row">
        <!-- user profile nav tabs content start -->
        <div class="col-lg-9">

          <div class="s_">

            <div class="tab-pane" id="profile" aria-labelledby="profile-tab" role="tabpanel">
              <!-- user profile nav tabs profile start -->

              <div class="card">
                <div class="card-content">
                  <div class="card-body">
                    <h5 class="card-title">
                        {{$user->first_name}} {{$user->last_name}} activity


                    
                      <a href="{{route('admin.users.show', $user->id)}}" class="btn btn-sm d-none d-sm-block float-right btn-light-secondary mb-2">
                        <i class="cursor-pointer bx bx-chevron-left font-small-3 mr-50"></i><span>Back</span> 
                      </a>
                      <a href="{{route('admin.users.show', $user->id)}}" class="btn btn-sm d-block d-sm-none btn-block text-center btn-light-secondary">
                        <i class="cursor-pointer bx bx-chevron-left font-small-3 mr-25"></i><span>Back</span>
                      </a>      
                    
  

                    </h5>

                    {{-- Handle the Activity table --}}
                    @if ($activity_count == 0 || $activity_count < 1)
                      <div class="no-record-sub">
                        <img src="{{asset('static/backend/assets/images/no/no-records.png')}}">
                        <h4>{{$user->first_name}} {{$user->last_name}} has no activities yet!</h4>
                      </div>
                    @endif

                    <ul class="widget-timeline mb-0">
                      @foreach ($user->activities as $activity)
                
                                              
                        <li class="timeline-items timeline-icon-secondary active">
                          @if ($activity->created_at !== null)
                            <div class="timeline-time">{{$activity->created_at->format('F, j ')}}</div>
                          @endif
                          
                          <h6 class="timeline-title">
                            
                            @if ($activity->signal == 'comment')
                              <a href="{{$activity->first_value_link}}">{{$activity->first_value}}</a>
                               reacted to
                              <a href="{{$activity->second_value_link}}">{{$activity->second_value}}</a>s <a href="{{$activity->activity_url}}">Post</a>
                            @endif

                            @if ($activity->signal == 'join')
                              <a href="#" target="_blank">{{$activity->first_value}}</a> joined Flooma
                            @endif

                          </h6>

                          @if ($activity->created_at !== null)
                            <p class="timeline-text">{{$activity->created_at->diffForHumans()}}</p>
                          @endif      

                          @if ($activity->signal !== null)
                            @if ($activity->signal == 'comment')
                              <div class="timeline-content">
                                <img src="{{asset('static/backend/app-assets/images/icon/pdf.png')}}" alt="document" height="23" width="19" class="mr-50">
                                  New Order.pdf
                              </div>
                            @endif

                            
                          @endif
                        </li>

                      @endforeach
      
                    </ul>  

                  </div>
                </div>
              </div>
              <!-- user profile nav tabs profile ends -->
            </div>
          </div>



        </div>
        <!-- user profile nav tabs content ends -->
        <!-- user profile right side content start -->
        <div class="col-lg-3">

          <div class="simple-statistic-backend card">
            <div class="d-flex">

              <div class="col-md-6 ssb-section">
                <p>Total Sales</p>
                <h3>51</h3>
              </div>
              
              <div class="col-md-6 ssb-section">
                <p>Total Earnings</p>
                <h3>$4.7K</h3>
              </div>

            </div>
          </div>

          <!-- user profile right side content related groups start -->
          <div class="card">
            <div class="card-content">
              <div class="card-body">
                <h6 class="card-title mb-1">
                    <small>
                        Last 3 Products from {{$user->name}}
                    </small>              
                </h6>

                <div class="media d-flex align-items-center mb-1">
                  <a href="JavaScript:void(0);">
                    <img src="{{asset('static/backend/app-assets/images/banner/banner-30.jpg')}}" class="rounded" alt="group image"
                      height="64" width="64" />
                  </a>
                  <div class="media-body ml-1">
                    <h6 class="media-heading mb-0"><small>Play Guitar</small></h6><small class="text-muted">2.8k
                      members (7 joined)</small>
                  </div>
                  <i class="cursor-pointer bx bx-show-alt text-primary d-flex align-items-center"></i>
                </div>

                <div class="media d-flex align-items-center mb-1">
                  <a href="JavaScript:void(0);">
                    <img src="{{asset('static/backend/app-assets/images/banner/banner-30.jpg')}}" class="rounded" alt="group image"
                      height="64" width="64" />
                  </a>
                  <div class="media-body ml-1">
                    <h6 class="media-heading mb-0"><small>Play Guitar</small></h6><small class="text-muted">2.8k
                      members (7 joined)</small>
                  </div>
                  <i class="cursor-pointer bx bx-show-alt text-primary d-flex align-items-center"></i>
                </div>
                
                <div class="media d-flex align-items-center mb-1">
                  <a href="JavaScript:void(0);">
                    <img src="{{asset('static/backend/app-assets/images/banner/banner-30.jpg')}}" class="rounded" alt="group image"
                      height="64" width="64" />
                  </a>
                  <div class="media-body ml-1">
                    <h6 class="media-heading mb-0"><small>Play Guitar</small></h6><small class="text-muted">2.8k
                      members (7 joined)</small>
                  </div>
                  <i class="cursor-pointer bx bx-show-alt text-primary d-flex align-items-center"></i>
                </div>

              </div>
            </div>
          </div>
          <!-- user profile right side content related groups ends -->


        </div>
        <!-- user profile right side content ends -->
      </div>
      <!-- user profile content section start -->
    </div>
  </div>
</section>

@stop





{{-- Start Js Vendors --}}
@section('vendor-js')

@stop{{-- End Js Vendors --}}

{{-- Start Js pages --}}
@section('pages-js')

<script src="{{asset('static/backend/app-assets/js/scripts/modal/components-modal.min.js')}}"></script>
<script src="{{asset('static/backend/app-assets/js/scripts/popover/popover.min.js')}}"></script>
@stop{{-- End Js pages --}}